apiVersion: apps/v1
kind: Deployment
metadata:
  name: <NAME>-<VERSION>
spec:
  selector:
    matchLabels:
      app: <NAME>-<VERSION>
  replicas: 1
  template:
    metadata:
      labels:
        app: <NAME>-<VERSION>
    spec:
      imagePullSecrets:
        - name: registry-key
      containers:
        - name: <NAME>-<VERSION>
          image: djlxs/<NAME>:<VERSION>
          ports:
            - containerPort: 80
